# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/atish/dev/Proto/mp3_encoder

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/atish/dev/Proto/mp3_encoder

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/atish/dev/Proto/mp3_encoder/CMakeFiles /home/atish/dev/Proto/mp3_encoder/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/atish/dev/Proto/mp3_encoder/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mp3_encoder

# Build rule for target.
mp3_encoder: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mp3_encoder
.PHONY : mp3_encoder

# fast build rule for target.
mp3_encoder/fast:
	$(MAKE) -f CMakeFiles/mp3_encoder.dir/build.make CMakeFiles/mp3_encoder.dir/build
.PHONY : mp3_encoder/fast

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/mp3_encoder.dir/build.make CMakeFiles/mp3_encoder.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/mp3_encoder.dir/build.make CMakeFiles/mp3_encoder.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/mp3_encoder.dir/build.make CMakeFiles/mp3_encoder.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/thread_handler.o: src/thread_handler.cpp.o

.PHONY : src/thread_handler.o

# target to build an object file
src/thread_handler.cpp.o:
	$(MAKE) -f CMakeFiles/mp3_encoder.dir/build.make CMakeFiles/mp3_encoder.dir/src/thread_handler.cpp.o
.PHONY : src/thread_handler.cpp.o

src/thread_handler.i: src/thread_handler.cpp.i

.PHONY : src/thread_handler.i

# target to preprocess a source file
src/thread_handler.cpp.i:
	$(MAKE) -f CMakeFiles/mp3_encoder.dir/build.make CMakeFiles/mp3_encoder.dir/src/thread_handler.cpp.i
.PHONY : src/thread_handler.cpp.i

src/thread_handler.s: src/thread_handler.cpp.s

.PHONY : src/thread_handler.s

# target to generate assembly for a file
src/thread_handler.cpp.s:
	$(MAKE) -f CMakeFiles/mp3_encoder.dir/build.make CMakeFiles/mp3_encoder.dir/src/thread_handler.cpp.s
.PHONY : src/thread_handler.cpp.s

src/wav.o: src/wav.cpp.o

.PHONY : src/wav.o

# target to build an object file
src/wav.cpp.o:
	$(MAKE) -f CMakeFiles/mp3_encoder.dir/build.make CMakeFiles/mp3_encoder.dir/src/wav.cpp.o
.PHONY : src/wav.cpp.o

src/wav.i: src/wav.cpp.i

.PHONY : src/wav.i

# target to preprocess a source file
src/wav.cpp.i:
	$(MAKE) -f CMakeFiles/mp3_encoder.dir/build.make CMakeFiles/mp3_encoder.dir/src/wav.cpp.i
.PHONY : src/wav.cpp.i

src/wav.s: src/wav.cpp.s

.PHONY : src/wav.s

# target to generate assembly for a file
src/wav.cpp.s:
	$(MAKE) -f CMakeFiles/mp3_encoder.dir/build.make CMakeFiles/mp3_encoder.dir/src/wav.cpp.s
.PHONY : src/wav.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... mp3_encoder"
	@echo "... rebuild_cache"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/thread_handler.o"
	@echo "... src/thread_handler.i"
	@echo "... src/thread_handler.s"
	@echo "... src/wav.o"
	@echo "... src/wav.i"
	@echo "... src/wav.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

